;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Block",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Dash.Cooldown",DevComment="")
+GameplayTagList=(Tag="Combo.End",DevComment="")
+GameplayTagList=(Tag="Combo.Start",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Amount",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Response",DevComment="")
+GameplayTagList=(Tag="Event.Hit.Check",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Block",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.CameraShake.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.End",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.Loop",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.Start",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Attack.Large",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Attack.Small",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Attack.Large",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Attack.Small",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Hit",DevComment="")
+GameplayTagList=(Tag="State.Blocking",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Invincible",DevComment="")

