;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Attack.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Block",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Block.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Dash.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.RangeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.RangeAttack.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SSRAttack",DevComment="SSR 3단공격")
+GameplayTagList=(Tag="Ability.Action.SSRAttack.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SSRAuraBlade",DevComment="SSR 검기")
+GameplayTagList=(Tag="Ability.Action.SSRAuraBlade.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SSRBlock",DevComment="SSR 블락")
+GameplayTagList=(Tag="Ability.Action.SSRBlock.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SSRDash",DevComment="SSR 대쉬")
+GameplayTagList=(Tag="Ability.Action.SSRDash.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SSRFinal",DevComment="SSR 필살기")
+GameplayTagList=(Tag="Ability.Action.SSRFinal.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SunFire",DevComment="화상")
+GameplayTagList=(Tag="Ability.Action.SunFire.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.TeleportDashAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.TeleportDashAttack.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Ultimate",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Ultimate.Cooldown",DevComment="")
+GameplayTagList=(Tag="Combo.End",DevComment="")
+GameplayTagList=(Tag="Combo.Start",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown.Duration",DevComment="")
+GameplayTagList=(Tag="Data.Cost.Stamina",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Amount",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Response",DevComment="")
+GameplayTagList=(Tag="Data.Damage.TickAmount",DevComment="태불망")
+GameplayTagList=(Tag="Data.Stun.Duration",DevComment="")
+GameplayTagList=(Tag="Event.Hit.Check",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Action.Hidden",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Block",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.CameraShake.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.CameraShake.UltimateHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.End",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.Loop",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.Start",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.HitFlash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Attack.Large",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Attack.Small",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Block",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Swing",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Ultimate",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Attack.Large",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Attack.Small",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.RangeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.RangeAttack.Start",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.UltimateFlash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SSR.AuraBlade.Charging",DevComment="SSR 검기 차징")
+GameplayTagList=(Tag="GameplayCue.SSR.AuraBlade.Fire",DevComment="SSS 검기 발사")
+GameplayTagList=(Tag="GameplayCue.SSR.AuraBlade.Hit",DevComment="SSR 검기 피격시 이펙트")
+GameplayTagList=(Tag="GameplayCue.SSR.Block.End",DevComment="SSR 블락 끝")
+GameplayTagList=(Tag="GameplayCue.SSR.Block.Start",DevComment="SSR 대쉬 시작")
+GameplayTagList=(Tag="GameplayCue.SSR.Block.Visual",DevComment="블락 VFX")
+GameplayTagList=(Tag="GameplayCue.SSR.Dash.End",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SSR.Dash.Start",DevComment="SSR 대쉬 시작")
+GameplayTagList=(Tag="GameplayCue.SSR.Final.Combo",DevComment="SSR 필살기 성공시 콤보")
+GameplayTagList=(Tag="GameplayCue.SSR.Final.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SSR.SunFire.End",DevComment="태불망 종료")
+GameplayTagList=(Tag="GameplayCue.SSR.SunFire.Loop",DevComment="태불망 진행")
+GameplayTagList=(Tag="GameplayCue.SSR.SunFire.Start",DevComment="태불망 시작")
+GameplayTagList=(Tag="State.Blocking",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Invincible",DevComment="")
+GameplayTagList=(Tag="State.Lock",DevComment="")
+GameplayTagList=(Tag="State.Stun",DevComment="")
+GameplayTagList=(Tag="State.Stun.Duration",DevComment="")
+GameplayTagList=(Tag="State.Sunfire",DevComment="")

