;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Block",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Action.RangeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.TeleportDashAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Action.SSRAttack",DevComment="SSR 3단공격")
+GameplayTagList=(Tag="Ability.Action.SunFire",DevComment="화상")
+GameplayTagList=(Tag="Ability.Action.TeleportDashAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Dash.Cooldown",DevComment="")
+GameplayTagList=(Tag="Combo.End",DevComment="")
+GameplayTagList=(Tag="Combo.Start",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Amount",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Response",DevComment="")
+GameplayTagList=(Tag="Data.Damage.TickAmount",DevComment="태불망")
+GameplayTagList=(Tag="Event.Hit.Check",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Action.Hidden",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Block",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.CameraShake.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.End",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.Loop",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.Dash.Start",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Attack.Large",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.SFX.Attack.Small",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Attack.Large",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Attack.Small",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SSR.SunFire.End",DevComment="태불망 종료")
+GameplayTagList=(Tag="GameplayCue.SSR.SunFire.Loop",DevComment="태불망 진행")
+GameplayTagList=(Tag="GameplayCue.SSR.SunFire.Start",DevComment="태불망 시작")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.RangeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.P1.VFX.RangeAttack.Start",DevComment="")
+GameplayTagList=(Tag="State.Blocking",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Invincible",DevComment="")
+GameplayTagList=(Tag="State.Lock",DevComment="")
+GameplayTagList=(Tag="State.MoveLock",DevComment="")

